#!/bin/sh

 # MIT License
 #
 # Copyright (C) 2018 - 2019 Intel Corporation. All rights reserved.
 #
 # Permission is hereby granted, free of charge, to any person obtaining a
 # copy of this software and associated documentation files (the "Software"),
 # to deal in the Software without restriction, including without limitation
 # the rights to use, copy, modify, merge, publish, distribute, sublicense,
 # and/or sell copies of the Software, and to permit persons to whom the
 # Software is furnished to do so, subject to the following conditions:
 #
 # The above copyright notice and this permission notice shall be included in
 # all copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.

if [[ $# != 1 ]] ; then
    echo "Usage: install pmwatch_<ver>.tar.bz2"
    exit
fi

if [ "${USER}x" != "rootx" ] ; then
    echo "Non-root user. Try again with root access!"
    exit
fi

TARBALL="$1"
if [ ! -f ${TARBALL} ] ; then
    echo "Invalid tarball!"
    exit
fi

BIN_DIR="bin64"
LIB_DIR="lib64"
SYSTEM_LIB64="lib64"
INSTALL_BASE="/opt/intel"
INSTALL_BASE_DIR="${INSTALL_BASE}/pmwatch"
PMWATCH_VER=${TARBALL:9:5}
PMWATCH_BASE_NAME=${TARBALL:0:-8}
INSTALL_DIR="${INSTALL_BASE}/${PMWATCH_BASE_NAME}"
LIBIPMCTL="libipmctl.so.3.1.0"
LIBIPMCTL_LESS="libipmctl.so.3"

if [ ! -d "${INSTALL_BASE}" ] ; then
    mkdir ${INSTALL_BASE}
    if [ $? -ne 0 ] ; then
        echo "Unable to create ${INSTALL_BASE}. Exiting..."
        exit
    fi
fi

sh -c "tar xf ${TARBALL} -C ${INSTALL_BASE}"
sh -c "chown root ${INSTALL_DIR}/${BIN_DIR}/pmwatch"
sh -c "chgrp root ${INSTALL_DIR}/${BIN_DIR}/pmwatch"
sh -c "chown root ${INSTALL_DIR}/${BIN_DIR}/pmwatch-stop"
sh -c "chgrp root ${INSTALL_DIR}/${BIN_DIR}/pmwatch-stop"

find_ipmctl=$( find /${SYSTEM_LIB64}/ -name ${LIBIPMCTL} )
if [ -z "${find_ipmctl}" ] ; then
    sh -c "mv ${INSTALL_DIR}/${LIB_DIR}/${LIBIPMCTL} /${SYSTEM_LIB64}/"
    sh -c "ln -s /${SYSTEM_LIB64}/${LIBIPMCTL} /${SYSTEM_LIB64}/${LIBIPMCTL_LESS}"
else
    find_ipmctl=$( find /${SYSTEM_LIB64}/ -name ${LIBIPMCTL_LESS} )
    if [ -z "${find_ipmctl}" ] ; then
        sh -c "ln -s /${SYSTEM_LIB64}/${LIBIPMCTL} /${SYSTEM_LIB64}/${LIBIPMCTL_LESS}"
    fi
fi

if [ -L ${INSTALL_BASE_DIR} ] ; then
    sh -c "rm -f ${INSTALL_BASE_DIR}"
fi
sh -c "ln -s ${INSTALL_DIR} ${INSTALL_BASE_DIR}"

echo "pmwatch ${PMWATCH_VER} is installed in ${INSTALL_BASE_DIR}"
echo ""
echo "Follow the below steps to start using pmwatch:"
echo "  cd ${INSTALL_BASE_DIR}"
echo "  source ./pmw_vars.sh"
echo ""
echo "Only root user has the the permission to run pmwatch!"
echo "Please configure ESXi in maintenance mode for pmwatch to work."
echo ""
